# Site settings
title: "Sotirios Vrachas"
image: /blob/home.jpeg
email: "sotirios @ vrachas.com"
description: "Sotirios Vrachas' Blog"
baseurl: ""
url: "http://www.vrachas.com"
twitter_username: sotiriosvrachas
github_username: sotiriosvrachas

# Build settings
highlighter: rouge
permalink: /:title
paginate: 99
#exclude: [""]
future: false
show_drafts: false

prose:
  rooturl: '_posts'
  siteurl: 'http://sotiriosvrachas.github.io/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'blob'
  ignore:
    - index.html
    - /css
    - /fonts
    - /js
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Image"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
